version: '3'
services:
  db:
    container_name: 'db_postgresql'
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db_postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'soerjo'
      POSTGRES_PASSWORD: 'soerjo123'
