version: '3'
services:
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    container_name: 'db_postgresql'
    image: postgres
    networks:
      - nesjs-network
    volumes:
      - ./db_postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'soerjo'
      POSTGRES_PASSWORD: 'soerjo123'

networks:
  nesjs-network:
